name: Test HTML Merge & Post-Processing

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ main ]
    paths:
      - 'scripts/step4_merge.py'
      - 'scripts/postprocess.py'
      - '.github/workflows/test_step4.yml'
      - 'inputs/non_translatable.html'
      - 'inputs/*_translations.json'

jobs:
  merge-and-process:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'  # Faster dependency installation
        
    - name: Install dependencies
      run: |
        pip install beautifulsoup4
        
    - name: Create output directory
      run: mkdir -p outputs
      
    - name: Run merge script (both translators)
      run: |
        python scripts/step4_merge.py \
          --html inputs/non_translatable.html \
          --deepl inputs/deepl_translations.json \
          --openai inputs/openai_translations.json \
          --output-deepl outputs/final_deepl_FR.html \
          --output-openai outputs/final_openai_FR.html
          
    - name: Post-process outputs
      run: |
        python scripts/postprocess.py --input outputs/final_deepl_FR.html --target-lang fr
        python scripts/postprocess.py --input outputs/final_openai_FR.html --target-lang fr
        
    - name: Verify outputs
      run: |
        echo "Generated files:"
        ls
